nerdfont: true

files:
  copy:
    - .env
    - .env.*

panes:
  - command: nvim
    focus: true
  - command: lazygit
    split: horizontal
    percentage: 40
  - command: pi
    split: vertical
    percentage: 50
