/**
 * Workmux "waiting" status for pending questions.
 *
 * `workmux-status.ts` (generated by `workmux setup`) reports only working/done,
 * so a run blocked on a question looks identical to one still churning. This
 * extension adds workmux's third state: while an `ask_user_question`
 * questionnaire is on screen, the tmux window and `workmux dashboard` show
 * waiting (💬) instead of working (🤖), which also makes the window a jump
 * target for `prefix + L` and sorts it to the top of the dashboard.
 *
 * Kept separate from workmux-status.ts because `workmux setup --hooks`
 * rewrites that file from a template embedded in the workmux binary.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

/**
 * Event bus channel published by @juicesharp/rpiv-ask-user-question while a
 * questionnaire awaits an answer. The channel name and its `{ active }` payload
 * are part of that package's stable event contract, so they are inlined rather
 * than imported: the extension tree and the pi package tree resolve separately,
 * and this extension must keep loading when the package is absent.
 */
const ASK_USER_BLOCKED_EVENT = "rpiv:ask-user:blocked";

export default function (pi: ExtensionAPI) {
  function setStatus(status: string) {
    pi.exec("workmux", ["set-window-status", status]).catch(() => {});
  }

  // Answering, cancelling, or erroring out returns the run to "working";
  // workmux-status.ts then settles it to "done" on agent_settled.
  pi.events.on(ASK_USER_BLOCKED_EVENT, (data) => {
    const active = (data as { active?: unknown } | null)?.active;
    setStatus(active === true ? "waiting" : "working");
  });
}
