[tools]
python = "latest"
node = "latest"
lua = "5.1"
neovim = "latest"
rust = "latest"
"npm:@tobilu/qmd" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
